# 環境
environ:
    none: none


################################################################################

trainer:
    name: ClassTrainer
    params:
        none: none

# log
logger:
    sample.endTrain:
        scale: iter
        freq:   1000000
    sample.printer:
        freq: 1
    sample.image:
        freq: 15
    sample.model_and_optims:
        freq: 25
    sample.validation:
        freq: 25

# データ系
dataset:
    name: MNISTtvt
    params:
        val_rate: 0.15

################################################################################

# データローダー
loader:
    name: SimpleLoader
    params:
        batch_size: 4
        shuffle: True
        num_workers: 6
        pin_memory: True

# モデル系
model:
    name: AlexNet
    params:
        none: none

# ロス関数
loss:
    name: L2loss
    params:
        gan_loss: 1
        l1_loss: 0.01
        tv_loss: 0
        lstruct: 0

# 使用する最適化手法
optimizer:
    name: AdaDelta
    params:
        lr: 0.0002
        beta_1: 0.5
        beta_2: 0.999
        epsilon:  0.0000001
